/// Flutter icons Medcare
/// Copyright (C) 2025 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Medcare
///      fonts:
///       - asset: fonts/Medcare.ttf
///
/// 
/// * Font Awesome 5, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL (https://github.com/FortAwesome/Font-Awesome/blob/master/LICENSE.txt)
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class Medcare {
  Medcare._();

  static const _kFontFam = 'Medcare';
  static const String? _kFontPkg = null;

  static const IconData tooth = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData general = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData gal = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lung = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData eye = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mouth = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ear = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData border_all = IconData(0xf84c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
